--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/David-pm-pl/Clothes
build-by-default: true
branches:
- master
projects:
  Clothes:
    path: ""
    icon: icon.png
    libs:
    - src: JinodkDevTeam/FormAPI/libFormAPI
      version: ^1.4.0-alpha
...
