--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/TungstenVn/Clothes
build-by-default: true
branches:
- master
projects:
  Clothes:
    path: ""
    icon: icon.png
    libs:
    - src: jojoe77777/FormAPI
      version: ^1.3
...
