---
name: Clothes
version: 5.0
main: TungstenVn\Clothes\Clothes
api: 4.0.0
mcpe-protocol: [361, 388, 389, 390, 407, 408, 418, 428, 440, 471, 475, 486]
author: TungstenVn
commands:
  clothes:
    description: Clothes commands
    aliases: ["clo"]
    permission: clothes.command
  cosplays:
    description: Clothes commands
    aliases: ["cos"]
    permission: cosplays.command
  nanny:
    description: Clothes commands
    permission: nanny.clothes.command

permissions:
  clothes.command:
    description: Clothes commands
    default: true
  cosplays.command:
    description: Clothes commands
    default: true 
  nanny.clothes.command:
    description: Clothes commands
    default: op
...
