---
name: Clothes
version: 7.2
main: TungstenVn\Clothes\Clothes
api: 5.0.0
author: TungstenVn
authors:
  - taylordevs

permissions:
  clothes.command:
    description: Clothes commands
    default: true
  cosplays.command:
    description: Clothes commands
    default: true 
  nanny.clothes.command:
    description: Clothes commands
    default: op
...
