---
name: Clothes
version: 6.6
main: TungstenVn\Clothes\Clothes
src-namespace-prefix: TungstenVn\Clothes
api: 4.0.0
mcpe-protocol: 534
author: TungstenVn
authors:
  - DavidGlitch04
commands:
  clothes:
    description: Clothes commands
    aliases: ["clo"]
    permission: clothes.command
  cosplays:
    description: Clothes commands
    aliases: ["cos"]
    permission: cosplays.command
  nanny:
    description: Clothes commands
    permission: nanny.clothes.command

permissions:
  clothes.command:
    description: Clothes commands
    default: true
  cosplays.command:
    description: Clothes commands
    default: true 
  nanny.clothes.command:
    description: Clothes commands
    default: op
...
