---
name: Clothes
version: 2.0.0
main: TungstenVn\Clothes\Clothes
api:
- 3.0.0
author: TungstenVn
commands:
  clo:
    description: Open clothes menu
  clothes:
    description: Open clothes menu
...
