---
name: Clothes
version: 7.1
main: TungstenVn\Clothes\Clothes
api: 4.0.0
mcpe-protocol: 582
author: TungstenVn
authors:
  - taylordevs

permissions:
  clothes.command:
    description: Clothes commands
    default: true
  cosplays.command:
    description: Clothes commands
    default: true 
  nanny.clothes.command:
    description: Clothes commands
    default: op
...
